package daytours.View;

import daytours.Controller.Booking;
import daytours.Model.Tours;
import daytours.Controller.Search;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
//import src.Search;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Eiríkur Atli Briem, Háskóli Íslands, eab12@hi.is
 */
public class Daytours extends javax.swing.JFrame {
   
    ArrayList<Tours> results = new ArrayList<Tours>();
    static ArrayList<Tours> results2 = new ArrayList<Tours>();
    Search newSearch = new Search();
    static Booking newBooking = new Booking();
    static Search newSearch2 = new Search();
    DefaultTableModel tableModel;
    //DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel();
    
    /**
     * Creates new form Daytours
     */
    public Daytours() {
        
        //Results = new JTable(tableModel);
        initComponents();
        tableModel = (DefaultTableModel) Results.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Results = new javax.swing.JTable();
        jTegund = new javax.swing.JComboBox();
        jTegundLabel = new javax.swing.JLabel();
        jArea = new javax.swing.JComboBox();
        jAreaLabel = new javax.swing.JLabel();
        jDifficulty = new javax.swing.JComboBox();
        jDifficultyLabel = new javax.swing.JLabel();
        jDateDay = new javax.swing.JComboBox();
        jDateLabel = new javax.swing.JLabel();
        jDurationLabel = new javax.swing.JLabel();
        jDuration = new javax.swing.JComboBox();
        jDateMonth = new javax.swing.JComboBox();
        jDateYear = new javax.swing.JComboBox();
        jMinPriceLabel = new javax.swing.JLabel();
        jMinPrice = new javax.swing.JSpinner();
        jMaxPriceLabel = new javax.swing.JLabel();
        jMaxPrice = new javax.swing.JSpinner();
        jLanguage = new javax.swing.JComboBox();
        jLanguageLabel = new javax.swing.JLabel();
        jPickup = new javax.swing.JCheckBox();
        jHandicap = new javax.swing.JCheckBox();
        jAvailableLabel = new javax.swing.JLabel();
        jAvailable = new javax.swing.JSpinner();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSearch.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jSearch.setText("Search");
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });

        Results.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Results.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Type", "Duration", "Difficulty", "Price", "Total Seats", "Available", "Language", "Pickup", "Handicap"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Results.setRowHeight(25);
        jScrollPane2.setViewportView(Results);

        jTegund.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jTegund.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ekkert valið", "sightseeing", "hiking", "horseriding", "city walk", "adventure" }));
        jTegund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTegundActionPerformed(evt);
            }
        });

        jTegundLabel.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jTegundLabel.setText("Type");

        jArea.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ekkert valið", "capital region", "west", "east", "north", "south" }));
        jArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAreaActionPerformed(evt);
            }
        });

        jAreaLabel.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jAreaLabel.setText("Area");

        jDifficulty.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jDifficulty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ekkert valið", "easy", "medium", "hard" }));

        jDifficultyLabel.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jDifficultyLabel.setText("Difficulty");

        jDateDay.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jDateDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jDateLabel.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jDateLabel.setText("Date");

        jDurationLabel.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jDurationLabel.setText("Duration");

        jDuration.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jDuration.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ekkert valið", "1.0", "2.0", "3.0", "4.0", "5.0", "6.0", "7.0", "8.0", "9.0", "10.0", " " }));

        jDateMonth.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jDateMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jDateMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateMonthActionPerformed(evt);
            }
        });

        jDateYear.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jDateYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "2016", "2017" }));

        jMinPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jMinPriceLabel.setText("Min Price");

        jMinPrice.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jMinPrice.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100000, 5000));
        jMinPrice.setOpaque(false);

        jMaxPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jMaxPriceLabel.setText("Max Price");

        jMaxPrice.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jMaxPrice.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100000, 5000));

        jLanguage.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLanguage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ekkert valið", "danish", "english", "german", "icelandic", "spanish" }));

        jLanguageLabel.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLanguageLabel.setText("Language");

        jPickup.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jPickup.setText("Hotel Pickup");
        jPickup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPickupActionPerformed(evt);
            }
        });

        jHandicap.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jHandicap.setText("Disabled friendly");

        jAvailableLabel.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jAvailableLabel.setText("Available Seats");

        jAvailable.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jAvailable.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTegund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTegundLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jAreaLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jDifficultyLabel)
                                        .addComponent(jAvailableLabel)
                                        .addComponent(jAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jDurationLabel))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jMinPriceLabel)
                                        .addComponent(jMinPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jMaxPriceLabel)
                                        .addComponent(jMaxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLanguageLabel, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jDateDay, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jDateYear, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jHandicap)
                                            .addGap(51, 51, 51)
                                            .addComponent(jPickup))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTegundLabel)
                        .addGap(3, 3, 3)
                        .addComponent(jTegund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAreaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDurationLabel)
                            .addComponent(jMinPriceLabel)
                            .addComponent(jDifficultyLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMinPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jMaxPriceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMaxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLanguageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDateLabel)
                    .addComponent(jAvailableLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDateDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHandicap)
                    .addComponent(jPickup)
                    .addComponent(jAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        tableModel.setRowCount(0);
        
        String area;
        if(jArea.getSelectedIndex() == 0) area = "";
        else area = String.valueOf(jArea.getSelectedItem());
        
        String difficulty;
        if(jDifficulty.getSelectedIndex() == 0) difficulty = "";
        else difficulty = String.valueOf(jDifficulty.getSelectedItem());
        
        double duration;
        if (jDuration.getSelectedIndex() == 0) duration = 0.0;
        else duration = Double.parseDouble(String.valueOf(jDuration.getSelectedItem()));
        
        String type;
        if (jTegund.getSelectedIndex() == 0) type = "";
        else type = String.valueOf(jTegund.getSelectedItem());
        
        String date;
        int day = Integer.parseInt(String.valueOf(jDateDay.getSelectedItem()));
        int month = Integer.parseInt(String.valueOf(jDateMonth.getSelectedItem()));
        int year = Integer.parseInt(String.valueOf(jDateYear.getSelectedItem()));
        if (day == 0 || month == 0 || year == 0) date = "";
        else date = String.valueOf(jDateDay.getSelectedItem())+"."+
                String.valueOf(jDateMonth.getSelectedItem())+"."+
                String.valueOf(jDateYear.getSelectedItem());
        
        String language;
        if (jLanguage.getSelectedIndex() == 0) language = "";
        else language = String.valueOf(jLanguage.getSelectedItem());
        
        int minPrice = Integer.parseInt(String.valueOf(jMinPrice.getValue()));
        
        int maxPrice = Integer.parseInt(String.valueOf(jMaxPrice.getValue()));
        
        boolean handicap = jHandicap.isSelected();
         
        boolean pickup = jPickup.isSelected();
        
        int availableSeats = Integer.parseInt(String.valueOf(jAvailable.getValue()));
           
        // double duration, String type, String difficulty, String area, int minPrice, 
        // int maxPrice, String language, boolean pickup, boolean handicap,
        // String date, int availableTickets
        results = newSearch.getResults(duration, type, difficulty, area, minPrice, 
                maxPrice, language, pickup, handicap, date, availableSeats);
        
        System.out.println(results.size());
        
        while (!results.isEmpty()) {
            Tours haha = results.get(results.size()-1);
                        
            Object[] input = {haha.getId(), haha.getDate(), haha.getType(), 
                haha.getDuration(), haha.getDifficulty(), haha.getPrice(), 
                haha.getSeatsTotal(), haha.getSeatsAvailable(), 
                haha.getLanguage(), //hotelPickup, handicapAccess};
                haha.getPickup(), haha.getHandicap()};
            
            tableModel.addRow(input);
            results.remove(results.size()-1);
            
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_jSearchActionPerformed

    private void jTegundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTegundActionPerformed
        
// TODO add your handling code here:
    }//GEN-LAST:event_jTegundActionPerformed

    private void jAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAreaActionPerformed

    private void jDateMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateMonthActionPerformed

    private void jPickupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPickupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPickupActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daytours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daytours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daytours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daytours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //newBooking.makeBooking(17, 20);
        
        /*
        // double duration, String type, String difficulty, String area, int minPrice, 
        // int maxPrice, String language, boolean pickup, boolean handicap,
        // String date, int availableTickets
        results2 = newSearch2.getResults(0.0 , "", "medium", "", 0, 0, "", false, false, "", 0);
        int counter = results2.size()-1;
        while (!results2.isEmpty()) {
            Tours haha = results2.get(counter);
            System.out.println( haha.getId() + " " + haha.getArea() + " " + haha.getPrice() + " " + haha.getLanguage() );
            results2.remove(counter);
            counter--;
        }
        */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daytours().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Results;
    private javax.swing.JComboBox jArea;
    private javax.swing.JLabel jAreaLabel;
    private javax.swing.JSpinner jAvailable;
    private javax.swing.JLabel jAvailableLabel;
    private javax.swing.JComboBox jDateDay;
    private javax.swing.JLabel jDateLabel;
    private javax.swing.JComboBox jDateMonth;
    private javax.swing.JComboBox jDateYear;
    private javax.swing.JComboBox jDifficulty;
    private javax.swing.JLabel jDifficultyLabel;
    private javax.swing.JComboBox jDuration;
    private javax.swing.JLabel jDurationLabel;
    private javax.swing.JCheckBox jHandicap;
    private javax.swing.JComboBox jLanguage;
    private javax.swing.JLabel jLanguageLabel;
    private javax.swing.JSpinner jMaxPrice;
    private javax.swing.JLabel jMaxPriceLabel;
    private javax.swing.JSpinner jMinPrice;
    private javax.swing.JLabel jMinPriceLabel;
    private javax.swing.JCheckBox jPickup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSearch;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jTegund;
    private javax.swing.JLabel jTegundLabel;
    // End of variables declaration//GEN-END:variables
}
